apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-logs
  labels:
    app: multitool-logs
spec:
  selector:
    matchLabels:
      app: multitool-logs
  template:
    metadata:
      labels:
        app: multitool-logs
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        command: ["tail", "-f", "/dev/null"]  # Чтобы контейнер не завершался
        volumeMounts:
        - name: varlog
          mountPath: /host/var/log
          readOnly: true
        securityContext:
          privileged: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
          type: Directory
      # Чтобы позволить multitool читать хостовые логи, даем права
      hostNetwork: true
     
