apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /nfs-share
    server: 192.168.0.199
