apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-containers
  template:
    metadata:
      labels:
        app: multi-containers
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
        - name: multitool
          image: wbitt/network-multitool
          command: ["tail", "-f", "/dev/null"]
          ports:
            - containerPort: 8080
