apiVersion: v1
kind: Service
metadata:
  name: multi-svc
spec:
  selector:
    app: multi-containers
  ports:
    - name: nginx-port
      protocol: TCP
      port: 9001
      targetPort: 80       # в контейнере nginx
    - name: multitool-port
      protocol: TCP
      port: 9002
      targetPort: 8080    # в контейнере multitool
